/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./../components/common-header/index.vue')['default']
    Loading: typeof import('./../components/loading/index.vue')['default']
    Message: typeof import('./../components/message/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const CommonHeader: typeof import('./../components/common-header/index.vue')['default']
  const Loading: typeof import('./../components/loading/index.vue')['default']
  const Message: typeof import('./../components/message/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}